# 20.07.21 15일차

---

# Tensorflow를 이용한 AI 기초

## - Tensorflow 설치

In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
print(tf.__version__)
print(tf.keras.__version__)

2.2.0
2.3.0-tf


## - Lamba layer 0

In [3]:
from tensorflow.keras import layers, models
import tensorflow.keras.backend as K
import numpy as np

In [4]:
x_test = np.array([[1,2,3],
                   [4,5,6]])

In [5]:
def func(x):
    return x*2

x = layers.Input(shape=(3,))  # Input은 layer가 아닌 tensor를 반환
y = layers.Lambda(func)(x)    # tensor를 넣어 layer 생성

model = models.Model(x, y)    # tensor와 layer 입력
model.summary()

y_pred = model.predict(x_test)
print('x_test : \n', x_test)
print('y_pred : \n', y_pred)

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
lambda (Lambda)              (None, 3)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
x_test : 
 [[1 2 3]
 [4 5 6]]
y_pred : 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]]


---

In [6]:
y = layers.Lambda(lambda x:x**2)(x)

model = models.Model(x, y)    # tensor와 layer 입력
model.summary()

y_pred = model.predict(x_test)

print('x_test : \n', x_test)
print('y_pred : \n', y_pred)

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
lambda_1 (Lambda)            (None, 3)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
x_test : 
 [[1 2 3]
 [4 5 6]]
y_pred : 
 [[ 1.  4.  9.]
 [16. 25. 36.]]


---

In [7]:
def func(x):
    return K.sum(x, axis=1, keepdims=True) # axis = 곱할 차원

y = layers.Lambda(func)(x)    # tensor를 넣어 layer 생성

model = models.Model(x, y)    # tensor와 layer 입력
model.summary()

y_pred = model.predict(x_test)
print('x_test : \n', x_test)
print('y_pred : \n', y_pred)

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
lambda_2 (Lambda)            (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
x_test : 
 [[1 2 3]
 [4 5 6]]
y_pred : 
 [[ 6.]
 [15.]]


---

### 조건을 이용하기 

In [8]:
# y = layers.Lambda(lambda x:4 if x>4 else x)(x)
y = layers.Lambda(lambda x: K.switch(x>4, 4*K.ones_like(x), x))(x)

model = models.Model(x, y)    # tensor와 layer 입력
model.summary()

y_pred = model.predict(x_test)
print('x_test : \n', x_test)
print('y_pred : \n', y_pred)

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
lambda_3 (Lambda)            (None, 3)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
x_test : 
 [[1 2 3]
 [4 5 6]]
y_pred : 
 [[1. 2. 3.]
 [4. 4. 4.]]


---

### 2개의 출력 만들기

In [9]:
yA, yB = layers.Lambda(lambda x: [x/2, x*2])(x)

model = models.Model(x, [yA, yB])
model.summary()

y_pred_A, y_pred_B = model.predict(x_test)
print('x_test : \n', x_test)
print('y_pred : \n', y_pred_A)
print('y_pred : \n', y_pred_B)

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
lambda_4 (Lambda)            [(None, 3), (None, 3)]    0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
x_test : 
 [[1 2 3]
 [4 5 6]]
y_pred : 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]
y_pred : 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [10]:
yA, yB = layers.Lambda(lambda x: [x[:, :-1], x[:, 2:]])(x)

model = models.Model(x, [yA, yB])
model.summary()

y_pred_A, y_pred_B = model.predict(x_test)
print('x_test : \n', x_test)
print('y_pred : \n', y_pred_A)
print('y_pred : \n', y_pred_B)

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
lambda_5 (Lambda)            [(None, 2), (None, 1)]    0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
x_test : 
 [[1 2 3]
 [4 5 6]]
y_pred : 
 [[1. 2.]
 [4. 5.]]
y_pred : 
 [[3.]
 [6.]]


---

## - Lambda layer 1

In [11]:
x_test = np.array([[-1],
                   [2]])

### sigmoid

In [12]:
x = layers.Input((1,))
y = layers.Activation('sigmoid')(x)

model = models.Model(x, y)
model.summary()

y_pred = model.predict(x_test)
print('y_pred : \n', y_pred)

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred : 
 [[0.26894143]
 [0.880797  ]]


In [13]:
y = layers.Lambda(lambda x: 1/(1+K.exp(-x)))(x)

model = models.Model(x, y)
model.summary()

y_pred = model.predict(x_test)
print('y_pred : \n', y_pred)

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
lambda_6 (Lambda)            (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred : 
 [[0.26894143]
 [0.880797  ]]


### tanh

In [14]:
y = layers.Activation('tanh')(x)

model = models.Model(x, y)
model.summary()

y_pred = model.predict(x_test)
print('y_pred : \n', y_pred)

Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred : 
 [[-0.7615942]
 [ 0.9640276]]


In [15]:
y = layers.Lambda(lambda x: (1-K.exp(-2*x)) / (1+K.exp(-2*x)))(x)
# y = layers.Lambda(lambda x: 2*(1/(1+K.exp(-2*x)))-1)(x)

model = models.Model(x, y)
model.summary()

y_pred = model.predict(x_test)
print('y_pred : \n', y_pred)

Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
lambda_7 (Lambda)            (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred : 
 [[-0.7615942]
 [ 0.9640276]]


### relu

In [16]:
y = layers.Activation('relu')(x)

model = models.Model(x, y)
model.summary()

y_pred = model.predict(x_test)
print('y_pred : \n', y_pred)

Model: "model_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred : 
 [[0.]
 [2.]]


In [17]:
y = layers.Lambda(lambda x: K.switch(x>0, x, K.zeros_like(x)))(x)
# y = layers.Lambda(lambda x: K.switch(x<0, K.zeros_like(x), x))(x)

model = models.Model(x, y)
model.summary()

y_pred = model.predict(x_test)
print('y_pred : \n', y_pred)

Model: "model_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
lambda_8 (Lambda)            (None, None)              0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred : 
 [[0.]
 [2.]]


---

## - Merge layers 0

In [18]:
x_test_A = np.array([[0,1], [4,5]])
x_test_B = np.array([[2,3], [6,7]])

xA = layers.Input(shape=(2,), name='xA')
xB = layers.Input(shape=(2,), name='xB')

### concatenate

In [19]:
# y = layers.Concatenate(name='concat')([xA, xB]) # 이어 붙인다.
y = layers.concatenate([xA, xB], name='concat')

model = models.Model(inputs=[xA, xB], outputs=y)
model.summary()

y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A\n', x_test_A)
print('x_test_B\n', x_test_B)
print('y_pred\n', y_pred)

Model: "model_12"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
xA (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
xB (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
concat (Concatenate)            (None, 4)            0           xA[0][0]                         
                                                                 xB[0][0]                         
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
 [[0 1]
 [4 5]]
x_test

### add

In [20]:
# y = layers.Add(name='add')([xA, xB])
y = layers.add([xA, xB], name='add')

model = models.Model(inputs=[xA, xB], outputs=y)
model.summary()

y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A\n', x_test_A)
print('x_test_B\n', x_test_B)
print('y_pred\n', y_pred)

Model: "model_13"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
xA (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
xB (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
add (Add)                       (None, 2)            0           xA[0][0]                         
                                                                 xB[0][0]                         
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
 [[0 1]
 [4 5]]
x_test

### multiply

In [21]:
# y = layers.Multiply(name='add')([xA, xB])
y = layers.multiply([xA, xB], name='add')

model = models.Model(inputs=[xA, xB], outputs=y)
model.summary()

y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A\n', x_test_A)
print('x_test_B\n', x_test_B)
print('y_pred\n', y_pred)

Model: "model_14"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
xA (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
xB (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
add (Multiply)                  (None, 2)            0           xA[0][0]                         
                                                                 xB[0][0]                         
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
 [[0 1]
 [4 5]]
x_test

---

## - nodes 0

In [22]:
# Tensor
x = layers.Input((1,), name='x')
y = layers.Input((1,), name='y')

# Layer
h = layers.Dense(1, name='h')
a = layers.Dense(1, name='a')
b = layers.Dense(1, name='b')

In [23]:
print('h._inbound_nodes\n', h._inbound_nodes)
print('h._outbound_nodes\n', h._outbound_nodes)

h._inbound_nodes
 []
h._outbound_nodes
 []


In [24]:
hx = h(x)
print('h._inbound_nodes\n', h._inbound_nodes)
print('h._inbound_nodes[0].input_tensors\n', h._inbound_nodes[0].input_tensors)
print('h._inbound_nodes[0].output_tensors\n', h._inbound_nodes[0].output_tensors)

h._inbound_nodes
h._inbound_nodes[0].input_tensors
 Tensor("x:0", shape=(None, 1), dtype=float32)
h._inbound_nodes[0].output_tensors
 Tensor("h/Identity:0", shape=(None, 1), dtype=float32)
